### ISSUE TITLE
images folder

### ISSUE THREAD

**Issue by manegame** [merazgasalim/prismic-repository-cloner#1]
Very nice workflow! Worked for me.

Only hiccup I had, was that the download command needed the images folder to exist. Maybe makes sense to include this in your repo or in the description

**Comment by merazgasalim** [comment]
Hi @manegame ! Sorry for the delayed reply.
I just added the images folder to the repo. The reason why it doesn't exist on GitHub is because it's empty folder and can't upload it so I added a small icon to it.

I'm happy because the repo is useful for you

Regards
Salim
